version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: micro-url-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
    driver: local
